author: ToniTang
name: InventorySerializer
main: us.rpvp.inventoryserializer.InventorySerializer
url: ${project.url}
version: ${project.version}

commands:
  kit:
    usage: /kit <arguments>
    description: InventorySerializer Main Command
    permission: invserializer.kit